Delete food entry
Lambda-School-Labs/nutrivurv-fe pull request #187
Opened 2020-08-11 23:31 UTC by alesslongaretti

# Description

Delete Food entry and add delete confirmation modal.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## How Has This Been Tested?

- [x] npm start

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] There are no merge conflicts

2020-08-12 01:41 UTC, ccsmith13 approved these changes

2020-08-12 23:42 UTC, dave-vazquez requested changes
let me take a peek at this bug before we merge

2020-08-13 00:43 UTC, dave-vazquez commented
alright, we good

2020-08-13 00:43 UTC, merged

2020-08-13 01:19 UTC, alesslongaretti commented
![](https://github.trello.services/images/mini-trello-icon.png) [Delete Food entry](https://trello.com/c/h2fnXntp/148-delete-food-entry)